### ISSUE TITLE
DRARI RAH LAPP KHDAMA GHIR HOWA WLAT KT3ATEL BASH TZIDK F ROSETTA 3ENDAKOM TB9AW TZEDO TZEDO TATLQAW SHI RAQM MASHI HOWA HADAK HHHHH 

### ISSUE THREAD

**Issue by GHOST690186** [m1dugh/RosettaStonks#100]
**Describe the bug**

**Browser**
- [ ] firefox
- [ ] chrome

**version**: 

**rosettastone product**
- [ ] Foundations
- [ ] Fluency builder

**To Reproduce**

**Expected behavior**

**Comment by T1ttySl4yer** [comment]
khoya kidrti hta khdmtiha mabgatx tkhdm liya makatzidx walo

**Comment by zacariahh** [comment]
lawalo rah zedt 9h chi 4j wla 5j db w matzad walo wakha ykon ma3rt chno

**Comment by GHOST690186** [comment]
tana bhalkom b9it knzid yshabli makhadamsh shi 5 j db tal lyoma l9it 30 h f ang hhhh

**Comment by GHOST690186** [comment]
mtb9awsh tzedo ghi tsnaw rah atetla9 likom . lab9ito ktzedo rah kt7seb likom lwe9t

**Comment by zacariahh** [comment]
> tana bhalkom b9it knzid yshabli makhadamsh shi 5 j db tal lyoma l9it 30 h f ang hhhh

nari la hhhhhhhhhhhhhhhhhhhhhhhhh chha hadi zedt chi 15h w db ana kmelt 15h b script khor dayr fhal auto clicker nari matgolhach tana tl3li chi 30h hhhhhhhhhhhhhhhhhhhhhh

**Comment by elswordexe** [comment]
> > tana bhalkom b9it knzid yshabli makhadamsh shi 5 j db tal lyoma l9it 30 h f ang hhhh
> 
> nari la hhhhhhhhhhhhhhhhhhhhhhhhh chha hadi zedt chi 15h w db ana kmelt 15h b script khor dayr fhal auto clicker nari matgolhach tana tl3li chi 30h hhhhhhhhhhhhhhhhhhhhhh

nta la tl3 lk ana rah mb9a tl3 lia walo hta btari9a l3adia

**Comment by theityasser** [comment]
> > > tana bhalkom b9it knzid yshabli makhadamsh shi 5 j db tal lyoma l9it 30 h f ang hhhh
> > 
> > 
> > nari la hhhhhhhhhhhhhhhhhhhhhhhhh chha hadi zedt chi 15h w db ana kmelt 15h b script khor dayr fhal auto clicker nari matgolhach tana tl3li chi 30h hhhhhhhhhhhhhhhhhhhhhh
> 
> nta la tl3 lk ana rah mb9a tl3 lia walo hta btari9a l3adia

khoya wakha  tsift liya dak script
ha cmpt discord@theityasser

**Comment by theityasser** [comment]
daba la activit had extension wlkin mzl ma tbadel walo wach ghir nsanaha????

**Comment by theityasser** [comment]
> mtb9awsh tzedo ghi tsnaw rah atetla9 likom . lab9ito ktzedo rah kt7seb likom lwe9t

khoya chhal t9eiban ntsana hit dartha lyoma??

**Comment by elswordexe** [comment]
> daba la activit had extension wlkin mzl ma tbadel walo wach ghir nsanaha????
m3rt hit kin li tigoulk tzad lih mn ba3d 3 yam.
lmohim hahowa script lakhor https://github.com/Twilight392/Rosetta-Fluency-Builder-script.git

**Comment by theityasser** [comment]
> > daba la activit had extension wlkin mzl ma tbadel walo wach ghir nsanaha????
> 
> m3rt hit kin li tigoulk tzad lih mn ba3d 3 yam. lmohim hahowa script lakhor https://github.com/Twilight392/Rosetta-Fluency-Builder-script.git
chookran
hadi fonction nhatha f console?
wach katkhdem bhal autoclicker 
ki andir nkhadamha??

**Comment by zacariahh** [comment]
noice

**Comment by am226** [comment]
> > > > daba la activit had extension wlkin mzl ma tbadel walo wach ghir nsanaha????
> > > 
> > > 
> > > m3rt hit kin li tigoulk tzad lih mn ba3d 3 yam. lmohim hahowa script lakhor https://github.com/Twilight392/Rosetta-Fluency-Builder-script.git
> > > chookran
> > > hadi fonction nhatha f console?
> > > wach katkhdem bhal autoclicker
> > > ki andir nkhadamha??
> 
> ah bhalha bhal autoclicker atdir inspect wlouhha flconsole y9ad yktbo lk flconsole type chi haja bach dkhl lscript

bot dyal roseta wach kay detecte script . galk bnadm siftoh fraude ?????

**Comment by wsmusashi** [comment]
> > tana bhalkom b9it knzid yshabli makhadamsh shi 5 j db tal lyoma l9it 30 h f ang hhhh
> 
> nari la hhhhhhhhhhhhhhhhhhhhhhhhh chha hadi zedt chi 15h w db ana kmelt 15h b script khor dayr fhal auto clicker nari matgolhach tana tl3li chi 30h hhhhhhhhhhhhhhhhhhhhhh

ara lna akhay script

**Comment by zacariahh** [comment]
https://github.com/Twilight392/Rosetta-Fluency-Builder-script.git HAHOWA CHOF 
 bhalha bhal autoclicker atdir inspect wlouhha flconsole y9ad yktbo lk flconsole type chi haja bach dkhl lscript

**Comment by GHOST690186** [comment]
allow pasting

**Comment by zacariahh** [comment]
ah f fire fox atkb lmra lwl allow pasting w dir entre w wraha t9dr paster 3adi
