### ISSUE TITLE
chi mrat 5dmat lia f B1 WLA B2 wbzaaf dlmrat la chnou l7l broujoula gali wa7d kayna update 5ra 7ssn wla ma3rt

### ISSUE THREAD

**Issue by grlod** [m1dugh/RosettaStonks#101]
**Describe the bug**

**Browser**
- [ ] firefox
- [ ] chrome

**version**: 

**rosettastone product**
- [ ] Foundations
- [ ] Fluency builder

**To Reproduce**

**Expected behavior**

**Comment by T1ttySl4yer** [comment]
Mazal maban walo sarha in sha Allah ikon xib haja

**Comment by salims44** [comment]
rah khdama ta f c1

**Comment by Isernon** [comment]
> rah khdama ta f c1

Khouya lah yrhemlik lwalidin gholya fin dayr lghalat  ana b1 mabghach yzid lya lwe9t.
3ndi version 3.0.1
Kanswb ex wlakin makaytaffichach lya extension bach nzid lwe9t automatiquement khasni ana nbrk 3liha o nzid lwe9t
Lbarh zdt 30 min o mzl ldb matzadt

**Comment by ayamithn** [comment]
> rah khdama ta f c1

swa3 ka ytzado f nefss lwe9t ?

**Comment by LoopWasTaken** [comment]
Ana jrbtha wzadtni 57h 7itach b9it knzid knzid ta dazt 24h 3ad ban dkchi o t9olbt db jrbt fkontat akhrin mkaytzadech ta mn b3d 24h

**Comment by tr0ssward** [comment]
> Ana jrbtha wzadtni 57h 7itach b9it knzid knzid ta dazt 24h 3ad ban dkchi o t9olbt db jrbt fkontat akhrin mkaytzadech ta mn b3d 24h

sat momkin discord?
