### ISSUE TITLE
HELP MANIFEST NOT VALID

### ISSUE THREAD

**Issue by fella118** [m1dugh/RosettaStonks#12]
HELP !!

![image](https://github.com/m1dugh/RosettaStonks/assets/173559551/973af94a-9263-4d1c-8ba8-d7a81729b62f)

**Comment by m1dugh** [comment]
It looks like you are not using chrome-based browser

**Comment by Beastyy7** [comment]
> It looks like you are not using chrome-based browser

I had the same issue. I had to go back to earlier versions for it to work.

**Comment by Iamblacksss** [comment]
What version?
