### ISSUE TITLE
I need info

### ISSUE THREAD

**Issue by Egre11t** [m1dugh/RosettaStonks#13]
I was trying the valid lesson that is really good for saving me time in uni, but, they can know I'm cheating? I'm using add times to simulate the time online, but I'm scared, can you give me information about that?

**Comment by m1dugh** [comment]
From what we know, the only way to know someone cheated is either you did more than 24h in a single day, or you have way too much time for the amount of completed lessons. Adding time and validating lessons via this extension has been widely tested and very few people were caught cheating apparently.
