### ISSUE TITLE
time

### ISSUE THREAD

**Issue by zakariac-f7** [m1dugh/RosettaStonks#15]
problem in Fluency Builder I try to add tile but the button doesn't work

**Comment by m1dugh** [comment]
Have you followed the readme ?
How have you installed the app ?

**Comment by zakariac-f7** [comment]
> Have you followed the readme ? How have you installed the app ?

yes i did in Fluency Builder i click on ADD nothing happened just like this video https://www.youtube.com/watch?v=IzyP6-bU_Ko the different is it show green on the extension it not like the video

**Comment by m1dugh** [comment]
How did you install the extension ?
What did you download ?

**Comment by m1dugh** [comment]
It is normal nothing happens if it is red. You have to enter a lesson

**Comment by zakariac-f7** [comment]
> How did you install the extension ? What did you download ?

rosettastonks.tar.gz last version unzip it load the folder  to browser that what i did

**Comment by m1dugh** [comment]
Did you start a course after having installed the extension ?

**Comment by zakariac-f7** [comment]
> Did you start a course after having installed the extension ?

her a record from my desktop https://www.youtube.com/watch?v=gXcUo-zfhpA  when i do the same thing on  Foundations work normal type for example 15 min click add its go to 0 that mean its valid but on Fluency Builder nothing happend sorry for my broken english

**Comment by Cougar16** [comment]
Same here ! Please update your extension

**Comment by m1dugh** [comment]
The extension is in rework, till then, either change language to use `foundations`, or debug it on your machine, since *it works on my machine*.

**Comment by zakariac-f7** [comment]
> The extension is in rework, till then, either change language to use `foundations`, or debug it on your machine, since _it works on my machine_.

thanks for your time
