### ISSUE TITLE
Fluency Builder time issue

### ISSUE THREAD

**Issue by BLITZzz324** [m1dugh/RosettaStonks#23]
**Describe the bug**

**Browser**

- [ ] chrome

**version**:  3.0.1

**rosettastone product**

- [ ] Fluency builder

I tried your solution in the issue  #20 but it doesn't work we need a tutorial video asap

**Comment by kishyassin** [comment]
Hi @BLITZzz324 
Thank you for your message. Regarding your problem, here are the steps to follow:

Please remove the extension first if necessary.
Make sure you have downloaded the rosettastonks-chrome.tar.gz file from the last released version.
If you're using Chrome, enable developer mode to load the unpackaged extension after extracting the file to a folder.
Go to Rosetta and complete at least one exercise in a course.
Once you have completed this exercise, check if the extension offers an input field to enter the time.
If this field does not appear, make sure to clear your browser cache and try again.

**Comment by BLITZzz324** [comment]
I already did but the time does not increase in the dashboard I think I'm doing something wrong making a tutorial video is what I need & thanks

**Comment by BLITZzz324** [comment]
> Hi @BLITZzz324 Thank you for your message. Regarding your problem, here are the steps to follow:
> 
> Please remove the extension first if necessary. Make sure you have downloaded the rosettastonks-chrome.tar.gz file from the last released version. If you're using Chrome, enable developer mode to load the unpackaged extension after extracting the file to a folder. Go to Rosetta and complete at least one exercise in a course. Once you have completed this exercise, check if the extension offers an input field to enter the time. If this field does not appear, make sure to clear your browser cache and try again.

bro la kenti mghribi werini fin ncontactek werini

**Comment by aymanbest** [comment]
same problem here as well @kishyassin wkha tantkml one exercise in a course o kn add time makitezadch f dashboard

**Comment by BLITZzz324** [comment]
> same problem here as well @kishyassin wkha tantkml one exercise in a course o kn add time makitezadch f dashboard

same ta ana wela sed9at katzad ghi chi sa3a w katla3 m3atla

**Comment by aymanbest** [comment]
> > same problem here as well @kishyassin wkha tantkml one exercise in a course o kn add time makitezadch f dashboard
> 
> same ta ana wela sed9at katzad ghi chi sa3a w katla3 m3atla

ila knt atela3 me3atla then there is no problem , the problem howa matela3ch ga3

**Comment by BLITZzz324** [comment]
> > > same problem here as well @kishyassin wkha tantkml one exercise in a course o kn add time makitezadch f dashboard
> > 
> > 
> > same ta ana wela sed9at katzad ghi chi sa3a w katla3 m3atla
> 
> ila knt atela3 me3atla then there is no problem , the problem howa matela3ch ga3

mera katle3 mera la i'm trying men gbila walo but gbila jrbt b'méthode 9dima matzad walo ta dazt ch7al tzad 15H

**Comment by aymanbest** [comment]
> > > > same problem here as well @kishyassin wkha tantkml one exercise in a course o kn add time makitezadch f dashboard
> > > 
> > > 
> > > same ta ana wela sed9at katzad ghi chi sa3a w katla3 m3atla
> > 
> > 
> > ila knt atela3 me3atla then there is no problem , the problem howa matela3ch ga3
> 
> mera katle3 mera la i'm trying men gbila walo but gbila jrbt b'méthode 9dima matzad walo ta dazt ch7al tzad 15H

ina method 9edima t9adr t linkiha njarab ta ana

**Comment by BLITZzz324** [comment]
> > > same problem here as well @kishyassin wkha tantkml one exercise in a course o kn add time makitezadch f dashboard
> > 
> > 
> > same ta ana wela sed9at katzad ghi chi sa3a w katla3 m3atla
> 
> ila knt atela3 me3atla then there is no problem , the problem howa matela3ch ga3

also rah dar modif f'code ila drabti tela

**Comment by BLITZzz324** [comment]
> > > > > same problem here as well @kishyassin wkha tantkml one exercise in a course o kn add time makitezadch f dashboard
> > > > 
> > > > 
> > > > same ta ana wela sed9at katzad ghi chi sa3a w katla3 m3atla
> > > 
> > > 
> > > ila knt atela3 me3atla then there is no problem , the problem howa matela3ch ga3
> > 
> > 
> > mera katle3 mera la i'm trying men gbila walo but gbila jrbt b'méthode 9dima matzad walo ta dazt ch7al tzad 15H
> 
> ina method 9edima t9adr t linkiha njarab ta ana

test version 2.0.1

**Comment by kishyassin** [comment]
@aymanbest 
@BLITZzz324 
oui t9ed t3ettel chi mrra ghir reload the extension and clear cache
o clear 7ta data d rosetta 
7it t9d tkon kaytzad ms fchi compt akhor knty deja fat7o hh
wla tzad fchi language akhor

ghan7awlo nriglo lblan as soon as possible and make a video to explain how to use
Thanks

**Comment by BLITZzz324** [comment]
> @aymanbest @BLITZzz324 oui t9ed t3ettel chi mrra ghir reload the extension and clear cache o clear 7ta data d rosetta 7it t9d tkon kaytzad ms fchi compt akhor knty deja fat7o hh wla tzad fchi language akhor
> 
> ghan7awlo nriglo lblan as soon as possible and make a video to explain how to use Thanks

bro kheli lia fin ncontactek wela discord asap 7it khass nzid lbnadem hours w howa mkhalesni

**Comment by BLITZzz324** [comment]
> @aymanbest @BLITZzz324 oui t9ed t3ettel chi mrra ghir reload the extension and clear cache o clear 7ta data d rosetta 7it t9d tkon kaytzad ms fchi compt akhor knty deja fat7o hh wla tzad fchi language akhor
> 
> ghan7awlo nriglo lblan as soon as possible and make a video to explain how to use Thanks

also kayn script akhor kizid hours & kikhdem doros but only f foundations

**Comment by kishyassin** [comment]
@BLITZzz324 Nessab HHHHHHHHHHH

**Comment by BLITZzz324** [comment]
> @BLITZzz324 Nessab HHHHHHHHHHH

not at all geltha z3ma la kenti developper ykhdem ta f fluency a part ca werina kinkhdemo b'extension hhhhhh

**Comment by kishyassin** [comment]
I see
jrrb clear data d rosetta o reloader extension chrji d v 3.0.2
rah ghatkhdm

**Comment by BLITZzz324** [comment]
> I see jrrb clear data d rosetta o reloader extension chrji d v 3.0.2 rah ghatkhdm

kankhdm b private browser à chaque fois kansedo w kan3awd w khdam b 3.0.2 mais rah wa9ila tra chi prob f'upload 7it tale3 lia 3.0.1 kankhdem 2 exercices w kanzid we9t mais walo stp a bro la kan momkin chi vid gheda thanks a lot

**Comment by BXRl** [comment]
> > I see jrrb clear data d rosetta o reloader extension chrji d v 3.0.2 rah ghatkhdm
> 
> kankhdm b private browser à chaque fois kansedo w kan3awd w khdam b 3.0.2 mais rah wa9ila tra chi prob f'upload 7it tale3 lia 3.0.1 kankhdem 2 exercices w kanzid we9t mais walo stp a bro la kan momkin chi vid gheda thanks a lot

malkom a jmami hhhh

**Comment by BLITZzz324** [comment]
> I see jrrb clear data d rosetta o reloader extension chrji d v 3.0.2 rah ghatkhdm

bro rah testit had sba7 tool khdama all good the only problem kit3tl bach it'afficha but anyway 7san

**Comment by kishyassin** [comment]
well Done 
@m1dugh CLOSE

**Comment by BXRl** [comment]
sat tool ra kant khdama normal lyouma mab9atch katzid l fluency builder f mra jrbt ga3 les solution walo ay 7aja gltiha hna drtha hhhh

**Comment by BLITZzz324** [comment]
> sat tool ra kant khdama normal lyouma mab9atch katzid l fluency builder f mra jrbt ga3 les solution walo ay 7aja gltiha hna drtha hhhh

khdam lik ?

**Comment by BXRl** [comment]
> > sat tool ra kant khdama normal lyouma mab9atch katzid l fluency builder f mra jrbt ga3 les solution walo ay 7aja gltiha hna drtha hhhh
> 
> khdam lik ?

kant khdama walakin db la 3ndk chi solution?

**Comment by hamzacoder07** [comment]
@aymanbest @kishyassin @BXRl @BLITZzz324 Drari ila ma7bstoch hadchi dyalkom wlah 7ta atmchiw fen trabaw hadchi li kadero rah 7chom o tazwiir ana 7adertkom wlah hta tmchiw fen trabaw rakom katla3bo bm3lomat [wliti katbi3o o tchriw feha](https://www.tiktok.com/@rosettabypass/video/7442609660651244855?is_from_webapp=1&sender_device=pc&web_id=7388830846754702853)
