### ISSUE TITLE
Fluency Builder 

### ISSUE THREAD

**Issue by ghost** [m1dugh/RosettaStonks#25]
**Describe the bug**
Fluency Builder Time Issue.

**Browser**
- [ ] chrome

**version**: latest

**rosettastone product**
- [ ] Fluency builder

**Expected behavior**
I guess the extension needs update it was working but suddenly this day it stopped I tried all the solutions that was working before but none of them worked I guess I can find help asap & thanks a lot

**Comment by m1dugh** [comment]
Latest isn't exactly a version, are you talking about version `3.0.2` ?
Can you describe the steps taken to add time ?

**Comment by BLITZzz324** [comment]
> Latest isn't exactly a version, are you talking about version `3.0.2` ? Can you describe the steps taken to add time ?

Yes Man I'm working with 3.0.2 and the I took the steps you shared in issue #20 it worked 2 days ago but today didn't worked I guess it needs update also I think you made a mistake in the upload of 3.0.2 version cause when I charge it on the browser It shows 3.0.1

**Comment by m1dugh** [comment]
There was a mistake indeed, you can download new version 3.0.2 with corrected manifest version.

**Comment by BLITZzz324** [comment]
> There was a mistake indeed, you can download new version 3.0.2 with corrected manifest version.

Bro I just tested it several times & it ain't working please try it yourself and do a tutorial video and thanks

**Comment by m1dugh** [comment]
Well it is working, I tested it, and others did too, so unless you can provide me with further informations, like extension logs, or *complete and detailed* explanation of what you have done, I won't be able to help you.

**Comment by BXRl** [comment]
> Well it is working, I tested it, and others did too, so unless you can provide me with further informations, like extension logs, or _complete and detailed_ explanation of what you have done, I won't be able to help you.

nope it dosent work welp i tried on several account and several devices

**Comment by m1dugh** [comment]
@BLITZzz324 in extensions page (`chrome://extensions`) you can click on `service worker` which will open a tab in which you can see the logs.

**Comment by BLITZzz324** [comment]
> @BLITZzz324 in extensions page (`chrome://extensions`) you can click on `service worker` which will open a tab in which you can see the logs.

![image](https://github.com/user-attachments/assets/fdd465fa-e85e-4401-8d01-bcec37f7ca20)
that's what I get

**Comment by aymanbest** [comment]
@BLITZzz324 discord dyalk

**Comment by astaxxxxx** [comment]
@aymanbest what i ll do after extracte files in a folder? i

**Comment by chilllguyyy** [comment]
> @BLITZzz324 in extensions page (`chrome://extensions`) you can click on `service worker` which will open a tab in which you can see the logs.

Hey, do you have a way I can contact you? I have a few questions to ask.

When will the "Fluency Builder" lessons validator be released?

**Comment by m1dugh** [comment]
It will be released when someone will take time to do it.
