### ISSUE TITLE
There is a problem in the Extension!!!

### ISSUE THREAD

**Issue by aminemoussaouie** [m1dugh/RosettaStonks#27]
**Describe the bug**

**Browser**
- [ ] firefox
- [x] chrome

**version**: 

**rosettastone product**
- [ ] Foundations
- [x] Fluency builder

**To Reproduce**

**Expected behavior**
I tried this extension today, and I do all the steps Step-by-Step, but after adding the time (60 minutes) and control the total time, I found nothing changed!
I wish that u can solve this as soon as possible.

**Comment by aminemoussaouie** [comment]
I tried this extension today, and I do all the steps Step-by-Step, but after adding the time (60 minutes) and control the total time, I found nothing changed!
I wish that u can solve this as soon as possible.

**Comment by BXRl** [comment]
> I tried this extension today, and I do all the steps Step-by-Step, but after adding the time (60 minutes) and control the total time, I found nothing changed! I wish that u can solve this as soon as possible.

ila 3ndk niveau a1 a2 ra katzid higher la

**Comment by ibrataha8** [comment]
@BXRl wach bsse7

**Comment by aminemoussaouie** [comment]
> > I tried this extension today, and I do all the steps Step-by-Step, but after adding the time (60 minutes) and control the total time, I found nothing changed! I wish that u can solve this as soon as possible.
> 
> ila 3ndk niveau a1 a2 ra katzid higher la

Ana 3ndi Fluency Builder ya3ni B2 C1.

**Comment by aminemoussaouie** [comment]
> did finish the whole lesson that you started when adding time, because in my case if i don't finish the lesson time wont be added, so try to finish the lesson and time will be added.

Do u mean that I should complete the whole unit?

**Comment by HamzaRbib** [comment]
yes, start a new lesson do one task of that lesson, go to the extension and add time, then complete current the lesson.

**Comment by abderrahmane047** [comment]
is there a way to remove the hours ?

**Comment by m1dugh** [comment]
@HamzaRbib it might be the solution indeed.

**Comment by m1dugh** [comment]
@abderrahmane047 No there is not.
