### ISSUE TITLE
the case when it works on fluency builder 

### ISSUE THREAD

**Issue by BXRl** [m1dugh/RosettaStonks#28]
so the extension actually work on fluency builder only in one condition if the account never collected time before fresh new still 0 on the timer you can add time but once there is time there you cant add time with it

**Comment by HITMAN098** [comment]
yup same here i had 2 hrs the popup to add time does not show

**Comment by m1dugh** [comment]
I will look into it later.

**Comment by abderrahmaneBouallaga** [comment]
> I will look into it later.

thanks

**Comment by astaxxxxx** [comment]
someone here can help me with this method?

**Comment by m1dugh** [comment]
It works as soon as you have finished the lesson apparently (by skipping the rest of the questions).
