### ISSUE TITLE
i added too much time??

### ISSUE THREAD

**Issue by Ayoub-vrs** [m1dugh/RosettaStonks#29]
Thanks you for this wonderful extension it worked 
I just want to ask you if i can modify it so that i can decrease the time on fluency builder
I accedentely added too much time and if the professor notice it, he will know that it is not a genuine time.

**Comment by HITMAN098** [comment]
nothing can be done i guess , just make an excuse

**Comment by m1dugh** [comment]
Indeed, nothing can be done.

**Comment by ISSAMBERK** [comment]
@Ayoub-vrs  tell me does this add time appeear to the prof can he see our time please tell me if you know

**Comment by Ayoub-vrs** [comment]
> @Ayoub-vrs  tell me does this add time appeear to the prof can he see our time please tell me if you know 

Yes

**Comment by ISSAMBERK** [comment]
@Ayoub-vrs For me I add 15 h in English, the prof will see all of it and I can pass the exam normally by the way where are you from
