### ISSUE TITLE
Fluency builder, extension straight up isn't working

### ISSUE THREAD

**Issue by Viperisuseful** [m1dugh/RosettaStonks#30]
**Describe the bug**
It doesn't work
I'm at B2 in French and C1 in english
when i go to the "service worker" thingy i get nothing just a blank network f12 dev thing

**Browser**
- [ ] chrome

**version**: 

**rosettastone product**
- [ ] Fluency builder

**To Reproduce**

**Expected behavior**
It should add hours

**Comment by aminemoussaouie** [comment]
Same problem, I wish to be fixed as soon as possible.

**Comment by m1dugh** [comment]
You have to finish the lesson for it to work.
