### ISSUE TITLE
Delete this project immediately; you are at risk and could face legal consequences. There are individuals selling this service for money.

### ISSUE THREAD

**Issue by hamzacoder07** [m1dugh/RosettaStonks#35]
[Look This Video 
](https://www.tiktok.com/@rosettabypass/video/7442609660651244855?is_from_webapp=1&sender_device=pc&web_id=7388830846754702853)

**Comment by m1dugh** [comment]
You should report this account to whomever might be competent, however, as I already told you, the code is distributed under MIT license, so I am not facing any legal issues myself. Please don't try to intimidate people or I shall report you to github.

I understand that it is a problem, but I am not the one selling services here.

Furthermore, there is no way to prove that this code was actually used to add time to people paying. I hardly see how giving your creds to someone to do your time can be legally reprehensible considering it might be legitimate time added.

**Comment by hamzacoder07** [comment]
@m1dugh I am just warning you, but you will bear the legal consequences that you will face.
