### ISSUE TITLE
they added double time for me

### ISSUE THREAD

**Issue by badruwu** [m1dugh/RosettaStonks#36]
the extension added double time , i tryed to add 700min and it added 1400min ,can you give me an extention that lowers the time thank you ,much appreciated
im very cooked if uni found out i was cheating time in fluency builder <3
I only needed 15h i already had around 3 to 4 hours

<img width="560" alt="Screenshot 2024-12-01 233129" src="https://github.com/user-attachments/assets/fd7b081a-a6fe-40d8-92e2-4be1d59761dd">

**Comment by gogoza** [comment]
_ have the same problem please help_

**Comment by m1dugh** [comment]
It is not possible as already answered many times in previous issues, please read issues before opening new ones.
