### ISSUE TITLE
big problem!!!

### ISSUE THREAD

**Issue by abderrahmane047** [m1dugh/RosettaStonks#37]
**Describe the bug**
it doesn't add real time if u check in with another browser u can clearly see that the time still remains the same it's changing only the view page (like inspect after rightclick )  
**Browser**
- [ ] firefox
- [X] chrome

**version**: 

**rosettastone product**
- [ ] Foundations
- [X] Fluency builder

**Comment by darthgam4er** [comment]
no its working

**Comment by abderrahmane047** [comment]
i added 33h hours on chrome on my laptop but after 2h, i checked it on my phone there's only 2h ?

**Comment by abderrahmane047** [comment]
> no its working


i added 33h hours on chrome on my laptop but after 2h, i checked it on my phone there's only 2h ?

**Comment by abderrahmane047** [comment]
solved
