### ISSUE TITLE
The hours are not being added to the accounts problem 3-12-2024

### ISSUE THREAD

**Issue by Salahajouaou** [m1dugh/RosettaStonks#46]
**Describe the bug**
The hours are not being added to the accounts

**Browser**
- [ ] Firefox
- [x] chrome

**version**: 

**rosettastone product**
- [x] Foundations
- [x] Fluency builder

**Expected behavior**
I suspect a high server load may cause the problem.

**Comment by m1dugh** [comment]
I very much doubt high load is the problem considering the size at which rosetta stone operates.
