### ISSUE TITLE
it's not working

### ISSUE THREAD

**Issue by salah3-jpg** [m1dugh/RosettaStonks#48]
**Describe the bug**

**Browser**
- [ ] firefox
- [x] chrome

**version**: 

**rosettastone product**
- [ ] Foundations
- [x] Fluency builder

**To Reproduce**
did everything right and did an excercise but its not working

**Expected behavior**
added time 
![image](https://github.com/user-attachments/assets/5eb8c409-7dae-4e44-b463-25ad736de02c)

**Comment by m1dugh** [comment]
Your browser looks a bit odd. Use proper chrome I guess.
