### ISSUE TITLE
hours not being added on Fluency builder

### ISSUE THREAD

**Issue by abdothiss** [m1dugh/RosettaStonks#49]
**Describe the bug**

**Browser**
- [X] firefox
- [X] chrome

**version**: 
latest

**rosettastone product**
- [ ] Foundations
- [X] Fluency builder

**To Reproduce**
i start an excercice 
the add minutes option shows
i add the minutes

**Expected behavior**
the hours doesnt get added , i tried both firefox and chrome but neither works , i tried other accounts and waited for feww hours.

the extention works great on Foundations tho.

**Comment by m1dugh** [comment]
It seems you need to finish the lesson you started to add the time. You can ignore the rest of the questions, it might work.

**Comment by salah3-jpg** [comment]
> It seems you need to finish the lesson you started to add the time. You can ignore the rest of the questions, it might work.

Does it count instantly or you need to wait ?

**Comment by chenten16** [comment]
also, while the actual lesson time gets counted correctly, any time I try to add using the extension doesn't count in the system at all. The time field shows up but the added time isn't being recorded

**Comment by abdothiss** [comment]
after 10 hours of posting the hours finnaly got added to all the accounts including the ones  which i completed the lesson. thank u Owner
