### ISSUE TITLE
V2.0.1 doesn't update time nor does it make any request. V1.0.1 does

### ISSUE THREAD

**Issue by Mart1t1** [m1dugh/RosettaStonks#5]
Unexpected behavior happened with Chrome version 114.0.5735.106, compiled for Mac OS 13.4 on x86/x64.

With V2.0.1, I can't see any request promise being printed in the terminal, and the time doesn't update as expected. 

V1.0.1 does work as expected as of today.

**Comment by m1dugh** [comment]
Could you be more precise when you say it doesn't work ?

**Comment by Mart1t1** [comment]
When it doesn't work, I mean time is not added.
I use foundations btw.

**Comment by m1dugh** [comment]
Be sure to check errors on the console, there may be an ad block or other software blocking the requests

**Comment by Mart1t1** [comment]
I had ad blockers, maybe it  has something to do with my issue. I can't test Rosetta stones right now, but I will keep you updated if I happen to use it again

**Comment by m1dugh** [comment]
It should be working well now
