### ISSUE TITLE
Hours dont get added on Fluency builder 

### ISSUE THREAD

**Issue by redaisdaking** [m1dugh/RosettaStonks#51]
**Describe the bug**
No matter how many attempts are made , on fluency product rosetta stonks stopped working , originally it was working good but lately this problem rised , I have done many attempts both on firefox and chrome changed lessons and even accounts buy the issue is still persistent 

**Browser**
- [ ] firefox
- [x] chrome

**version**: 

**rosettastone product**
- [x] Fluency builder

**To Reproduce**
1. Go to any lesson on fluency builder
2. Start the extension and do the usual steps
3. Add hours 
4. Hours won't count

**Comment by Veyos777** [comment]
I guess there is a problem right now with Rosetta Stone not only the extension even if you tried to work manually no time will be added

**Comment by moataz2558** [comment]
prepare yourself for 1000 hours added

**Comment by redaisdaking** [comment]
> I guess there is a problem right now with Rosetta Stone not only the extension even if you tried to work manually no time will be added

really? that explains why its like this , but it really is working pretty fine tho i mean with foundations
