### ISSUE TITLE
Anyone has a problem with time adding for foundations, i can't add time 

### ISSUE THREAD

**Issue by moondust011** [m1dugh/RosettaStonks#54]
**Describe the bug**

**Browser**
- [ ] firefox
- [x] chrome

**version**: 

**rosettastone product**
- [x] Foundations
- [ ] Fluency builder

**To Reproduce**

**Expected behavior**

**Comment by Veyos777** [comment]
There is a problem in Rosetta Stone platform the hours will be added automaticaly when it's solved eitherwise time won't be added even if you work manually
