### ISSUE TITLE
MORROCO STUDENT WARNING!!!  STUDENT GET CAUGHT USING THE SCRIPT 

### ISSUE THREAD

**Issue by GN1111-pixel** [m1dugh/RosettaStonks#58]
![WhatsApp Image 2024-12-06 à 00 11 07_597a4380](https://github.com/user-attachments/assets/6f7615d3-a872-4976-a8ad-29408ff77503)

**Comment by ismailkanibou** [comment]
hhhhh

**Comment by M4ds1506** [comment]
fin hna ?

**Comment by Arthur-code01** [comment]
> ![WhatsApp Image 2024-12-06 à 00 11 07_597a4380](https://private-user-images.githubusercontent.com/190390336/393087219-6f7615d3-a872-4976-a8ad-29408ff77503.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0OTc0NTUsIm5iZiI6MTczMzQ5NzE1NSwicGF0aCI6Ii8xOTAzOTAzMzYvMzkzMDg3MjE5LTZmNzYxNWQzLWE4NzItNDk3Ni1hOGFkLTI5NDA4ZmY3NzUwMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxNDU5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjIwODlkY2U1NTg1OGM0ZmUwYjBlNzFkY2IwOWFiZDhmYWMxMzIwNDRiZGE0MjdhNjRjZjE2NThkN2JlOWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lVudU_LWV3iQTbm9a_yn9C6Wi28JpP3n9ECaAtMNCPI)

ach daro m3ahom??????

**Comment by Arthur-code01** [comment]
ach daro m3ahom????

**Comment by itsAlonebtw** [comment]
> ach daro m3ahom????

hado ens marrakech madaro m3ahom walo galo lihom gha mat3awdohash

**Comment by moondust011** [comment]
kifach ENS Marrakech o tswira mktub fiha universite hassan 2 ?
ana chak had tswira machi 3la script ymkn li gama kmlo sway3 dyal rosetta 7it tawa7d fihum madarb 30 hrs

**Comment by GN1111-pixel** [comment]
BTW RAH KHASK DIR 15H ANGLAIS 15H FRANCAIS

**Comment by Arthur-code01** [comment]
> > ach daro m3ahom????
> 
> hado ens marrakech madaro m3ahom walo galo lihom gha mat3awdohash

kifch marrakech o mktoba hassan 2 casa??

**Comment by Arthur-code01** [comment]
> BTW RAH KHASK DIR 15H ANGLAIS 15H FRANCAIS

sat mnin jbti had screen??

**Comment by GN1111-pixel** [comment]
L9ITHA F GROUP DPROMO DYALNA D ENSA

**Comment by Arthur-code01** [comment]
> L9ITHA F GROUP DPROMO DYALNA D ENSA

ina ensa????

**Comment by GN1111-pixel** [comment]
SCREEN L9ITHA GHIR F GRP D CHAT DYAL PROMO WSAF HIT BZAF F ENSA DYALNA KAYSTA3MLO AUTOCLICKER BTW ENSA MARRAKECH

**Comment by kishyassin** [comment]
Had list dyal les admis fchi concours 
mzwra , aslan la derniere colonne mktoba b langlais hh

@m1dugh  please Close

**Comment by Arthur-code01** [comment]
> Had list dyal les admis fchi concours mzwra , aslan la derniere colonne mktoba b langlais hh
> 
> @m1dugh please Close

yeah tana la7dtha dkchi 3lch knswl o 9lbt ml9itch had liste g3

**Comment by Arthur-code01** [comment]
> SCREEN L9ITHA GHIR F GRP D CHAT DYAL PROMO WSAF HIT BZAF F ENSA DYALNA KAYSTA3MLO AUTOCLICKER BTW ENSA MARRAKECH

t2kd mnha asat wch bsh ola la

**Comment by GN1111-pixel** [comment]
OKEY ANA GHIR L9ITHA PARTAJITHA BACH TRDO BALKOM WSAF 
MHM I LL TRY T FIND OUT W NRD 3LIKOM

**Comment by Arthur-code01** [comment]
> OKEY ANA GHIR L9ITHA PARTAJITHA BACH TRDO BALKOM WSAF MHM I LL TRY T FIND OUT W NRD 3LIKOM

sf lai7fdek abro ty sm
