### ISSUE TITLE
File not found error + time doesn't add up

### ISSUE THREAD

**Issue by a78000** [m1dugh/RosettaStonks#6]
Hello,

Context:
- Using Chrome and latest version for Rosetta Stonks
- Stonks popup is green (so should be ready)
- Product : Foundations
- Lang: KR

BEFORE trying to add time, there is this error in the console of the extension
'Failed to load resource: net::ERR_FILE_NOT_FOUND' at index.js:1

AFTER trying to add time : 
GET chrome-extension://ihflljjkdnkkhjcmnpebkflldpbcbone/dist/index.js net::ERR_FILE_NOT_FOUND at index.html:21

Same error on 3 different computers (Windows and Ubuntu)

**Comment by gogo94210** [comment]
I'm getting the same error, on Opera, using Fluency Builder for german

**Comment by aderugy** [comment]
Hello, you can try using my fork on my github, I haven’t made a pr yet because it’s not a clean fix but it worked for me (foundations)

**Comment by m1dugh** [comment]
It should be all fixed by now @aderugy .
