### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Hzmoulchi** [m1dugh/RosettaStonks#64]

**Comment by molmotor-learnz** [comment]
tbe3 dakchi ligalk f readme, mora matzidha f extensions dialk sir khdm 3adi f fluency builder. mora matkhdm chi 2 questions, wrek 3la extension wkteb chhal mn minute bghiti tzid matalan 300, sf wkml lkhdma 3adi, khdm chi 3 wla 4 exercices
sf wkhrej ghatl9aha tzadetlik

**Comment by mohamedbenhandil** [comment]
Lah ihfdek a bro

**Comment by XYASSIV** [comment]
DRARI CH7AL NTSNAW BACH ITZADO SWAY3
