### ISSUE TITLE
@speedy79S the extention dont work 

### ISSUE THREAD

**Issue by Arthur-code01** [m1dugh/RosettaStonks#67]
**Describe the bug**
i see that u added an option to decrease hours but the extention dont work

**Browser**
- [x] chrome

**version**: 

**rosettastone product**
- [x] Fluency builder

**To Reproduce**

**Expected behavior**

@speedy79S

![image](https://github.com/user-attachments/assets/e20153ed-1a86-456b-b8c9-c899f8a762df)
![image](https://github.com/user-attachments/assets/6d9883e6-0c94-4b7b-950c-0a74646e827a)

**Comment by m1dugh** [comment]
Please do not open issues here, but directly on his repo.

**Comment by Arthur-code01** [comment]
> Please do not open issues here, but directly on his repo.

i cant find an issues tab on his repo im sorry bro <3
