### ISSUE TITLE
Add Time Issue

### ISSUE THREAD

**Issue by cheerios124** [m1dugh/RosettaStonks#7]
Hello,

Recently I've been using this program to finish my Rosetta Stone to save a couple of hours of homework. While the validate lesson button works perfectly and I am satisfied with its function, the add time seems to not work. Using the latest version of the program, the add time is able to be clicked without error (unless the error shows somewhere else.) I've waited 24 hours to see if the time changed but it has not. I am using the program on an Opera browser; is there something wrong with the code itself or how I downloaded it?

**Comment by cheerios124** [comment]
Let me know if there are any other questions that can further assist in solving the issue

**Comment by m1dugh** [comment]
Did you download the `RosettaStonks.tar.gz` in the latest release ?

**Comment by m1dugh** [comment]
I tested on chromium, everything works as expected, could you add more precision ?

**Comment by cheerios124** [comment]
I'm using Opera for my browser and downloaded the RosettaStonks.tar.gz file. The validator button works but the add time still doesn't work. I've tried pretty much everything (Reinstalling, etc.) Should I try a different browser or is there something I'm doing wrong?

**Comment by cheerios124** [comment]
All I need to do to add the time is to just add a specific number of minutes and click add time right?

**Comment by AxanAmine** [comment]
@m1dugh hello , yea the same problem for me , i just keep hitting it but nothing show up , is there a problem ?

**Comment by AxanAmine** [comment]
https://www.youtube.com/watch?v=IzyP6-bU_Ko&ab_channel=AmineYuuki 
here is a video that shows the problem , i think its because i have to login through the university website (i have no other option) 
or its something else , please feel free to hit me up , im ready to help u with anything 
thank u for ur time

**Comment by cheerios124** [comment]
I use foundations instead of that, but the validate lesson works for foundation. The add time button is clickable and seems to work, but time on the report pdf does not update.

**Comment by m1dugh** [comment]
The add time feature should work at least on foundations, if not check the logs in your browser console, see it there is anything related to rosetta stonks.

I will try to fix the add time feature for fluency builder ASAP.

**Comment by m1dugh** [comment]
If you are using Fluency builder, it should be fixed, please try to download the latest *release* and try again as I am not able to replicate your bug.

**Comment by AxanAmine** [comment]
@m1dugh unfortunately, it didn't get fixed, i'm not sure if its because of the university blocked something , i actually have no idea , anyway if there's a possibility to talk privately, i ll be happy to provide u access to my university account so you can check

**Comment by m1dugh** [comment]
I checked up with some people that had similar problem, it turned out they didn't properly extract the archive file.

As a reminder :
- download `rosettastonks.tar.gz` from the latest release
- to unpack `tar xvf rosettastonks.tar.gz`
- The load extension in your browser (maybe opera is the cause, I tried on chromium and brave)
- In the extension page of your browser, after having used the extension, check if there is no error on the extension card

You can also check if there are some errors in the developper console when you use the extension.

**Comment by cheerios124** [comment]
I tried this process again on Brave. 

Not sure what you mean by tar xvf rosettastonks.tar.gz. I assume its something you run in the terminal since I use mac. Doesn't work. I unzipped the file, imported into brave, and checked the console. It's giving me this error: Uncaught (in promise) SyntaxError: Unexpected end of JSON input. How can I fix this?

**Comment by cheerios124** [comment]
never mind. it works. 

thank you for all of your help.

**Comment by AxanAmine** [comment]
@ cheerios124 could you please share what you did differently this time? bcz i tried brave too and still not working 
![Screenshot 2024-04-08 211407](https://github.com/m1dugh/RosettaStonks/assets/148222190/1fda737a-3476-43c0-88d1-b0f0c8de2985)

**Comment by stalin182** [comment]
How do you solve that problem. I have the same problem i can do flency builder

**Comment by stalin182** [comment]
the validate lesson doesn't work

**Comment by griffin8581** [comment]
@m1dugh 
For me it's very strange, add time doesn't work at all! for fluency builder of course!

learn.rosettastone.com/:1 A preload for 'https://learn.rosettastone.com/static/media/RSNotoSans-Regular.6ce6085a.woff2' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.

**Comment by griffin8581** [comment]
@m1dugh 
also:
Unchecked runtime.lastError: The message port closed before a response was received.
learn.rosettastone.com/:1 Unchecked runtime.lastError: The message port closed before a response was received.
learn.rosettastone.com/:1 Unchecked runtime.lastError: The message port closed before a response was received.
learn.rosettastone.com/:1 Unchecked runtime.lastError: The message port closed before a response was received.
learn.rosettastone.com/:1 Unchecked runtime.lastError: The message port closed before a response was received.
learn.rosettastone.com/:1 Unchecked runtime.lastError: The message port closed before a response was received.
7Third-party cookie will be blocked. Learn more in the Issues tab.
learn.rosettastone.com/:1 Third-party cookie will be blocked. Learn more in the Issues tab.
/courses:1 Third-party cookie will be blocked. Learn more in the Issues tab.
/course/communications-pratiques-b1:1 Third-party cookie will be blocked. Learn more in the Issues tab.
/course/communications-pratiques-b1/fixer-un-rendez-vous/5/1:1 Third-party cookie will be blocked. Learn more in the Issues tab.
/course/communications-pratiques-b1/voyage-d-affaires:1 Third-party cookie will be blocked. Learn more in the Issues tab.
/course/communications-pratiques-b1/voyage-d-affaires/3/1:1 Third-party cookie will be blocked. Learn more in the Issues tab.
1:1 Third-party cookie will be blocked. Learn more in the Issues tab.
