### ISSUE TITLE
to owner i can't validate lessons in fluency builder

### ISSUE THREAD

**Issue by ganar19** [m1dugh/RosettaStonks#75]
**Describe the bug**

**Browser**
- [. ] firefox
- [ ] chrome

**version**: 

**rosettastone product**
- [ ] Foundations
- [. ] Fluency builder

**To Reproduce**

**Expected behavior**

**Comment by m1dugh** [comment]
Feature is not available for now.

**Comment by moha20065** [comment]
> Feature is not available for now.

Can u answer me 
The problem is on fluency builder or Rosetta ?
I'm talking about adding time
