### ISSUE TITLE
drari chiwahd isovina

### ISSUE THREAD

**Issue by KHlil0222** [m1dugh/RosettaStonks#76]
darir li rando discord ola insta iwarini kufach nsaaybo hadchi mabghach

**Comment by da7iarosetta** [comment]
Wa7d galli 3tink 50 dh

**Comment by aob-bi** [comment]
drari brojola lma 3At9o db rosetta ba9i liha 9al mn nhar w mktakhdmch li 3Ndhom B1 w B2
chi hal layrhm lalidin

**Comment by ilovetokilldemons** [comment]
> Wa7d galli 3tink 50 dh

w malk azbi rah business hada hhh
