### ISSUE TITLE
li rando insta ola discord iwarin kifach nsaybo hadchi mabghach

### ISSUE THREAD

**Issue by KHlil0222** [m1dugh/RosettaStonks#77]
chi wahd iwarinnaaaa

**Comment by ilovetokilldemons** [comment]
rah char7in tema

**Comment by KHlil0222** [comment]
> rah char7in tema

marftch dart koulchi ola walo

**Comment by KHlil0222** [comment]
> rah char7in tema

t9dar tgad mraya ??

**Comment by da7iarosetta** [comment]
> rah char7in tema

Khouya fach kat installi l extension f mozilla ki kaddir tzid biha swaye3 ?
