### ISSUE TITLE
chi updates 3la kifach n9so swaye3 wla something similar walo ?

### ISSUE THREAD

**Issue by ilovetokilldemons** [m1dugh/RosettaStonks#78]

**Comment by boulahya01** [comment]
hhhhhhhhhhhhhhhh contactit support mbghawch galoli sir l idara dyalk

**Comment by ilovetokilldemons** [comment]
hhh

**Comment by moha20065** [comment]
> hhhhhhhhhhhhhhhh contactit support mbghawch galoli sir l idara dyalk

Passi li link d support

**Comment by Tab1000j** [comment]
lkhot ana ba9i ma 3rft 7ta mnin ghanteleharger dossier la momkin xi mosa3ada

**Comment by aminessbaa** [comment]
> hhhhhhhhhhhhhhhh contactit support mbghawch galoli sir l idara dyalk

cheno 9alolik idaraa alhbib
