### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by salah3-jpg** [m1dugh/RosettaStonks#80]
**Describe the bug**

**Browser**
- [ x] firefox
- [x ] chrome

**version**: 

**rosettastone product**
- [ ] Foundations
- [x ] Fluency builder

no hours added in 2 days

**Comment by moha20065** [comment]
Did you find the solution

**Comment by elswordexe** [comment]
same probleme

**Comment by moha20065** [comment]
> same probleme

Do you have another script or extension

**Comment by zacariahh** [comment]
> > same probleme
> 
> Do you have another script or extension

sat tanta mabgatch tkdem lik yak?? w chre7 liya dak commentaire lwl layhfdek mafhemt walo

**Comment by wsmusashi** [comment]
guys is it solved ?

**Comment by elswordexe** [comment]
wla lwa9t makitzadch ga3 hta bla lextension

**Comment by zacariahh** [comment]
kitzad gha chwiya 9rit mn neyti 1h tzadt 15min wtffffff

**Comment by fath0l** [comment]
> > > same probleme
> > 
> > 
> > Do you have another script or extension
> 
> sat tanta mabgatch tkdem lik yak?? w chre7 liya dak commentaire lwl layhfdek mafhemt walo

khoyaa kano kitzado swaya3 wlkin db la wlaw kitzado ghir l level A afe m3rt mnach lblan

**Comment by ilovetokilldemons** [comment]
a walo ymkn mab9atch khdama

**Comment by zacariahh** [comment]
tkhwerna
