### ISSUE TITLE
makhdmax al khot f fluency builder?

### ISSUE THREAD

**Issue by Tab1000j** [m1dugh/RosettaStonks#81]
**Describe the bug**

**Browser**
- [ ] firefox
- [ ] chrome

**version**: 

**rosettastone product**
- [ ] Foundations
- [ ] Fluency builder

**To Reproduce**

**Expected behavior**

**Comment by fath0l** [comment]
kant khadama wlkin had lyamat m3rftch 3lach mab9atch khdama

**Comment by Tab1000j** [comment]
> kant khadama wlkin had lyamat m3rftch 3lach mab9atch khdama

axmen niveau nta a khouya wax b1 b2?
