### ISSUE TITLE
@m1dugh no hours added im waiting 2 days its still work or not?

### ISSUE THREAD

**Issue by Arthur-code01** [m1dugh/RosettaStonks#85]
**Describe the bug**

**Browser**
- [x] firefox
- [x] chrome

**version**: 

**rosettastone product**
- [x] Fluency builder

**To Reproduce**

**Expected behavior**
@m1dugh please help

**Comment by zacariahh** [comment]
me too it does not work for me

**Comment by matrex185** [comment]
me too

**Comment by fath0l** [comment]
> me too

me too bro but A level its done not like B level what the solution now

**Comment by Twilight392** [comment]
use this script, I found it and put it in my account https://github.com/Twilight392/Rosetta-Fluency-Builder-script.git

**Comment by MOSHIPOSHIONE** [comment]
> use this script, I found it and put it in my account https://github.com/Twilight392/Rosetta-Fluency-Builder-script.git

explain lay7fdk

**Comment by salah3-jpg** [comment]
> use this script, I found it and put it in my account https://github.com/Twilight392/Rosetta-Fluency-Builder-script.git

explain

**Comment by zacariahh** [comment]
> use this script, I found it and put it in my account https://github.com/Twilight392/Rosetta-Fluency-Builder-script.git

CHRE7 LINA BDARIJA W BDEBT

**Comment by matrex185** [comment]
tkono 7alin rosseta fi site o moraha t7ol chi tamrin 3andak tamak dir click liman bi souri o dir inspect ghatkon hiya lakhra ghaytla3 lik tableau lta7t kayna console copier script o collih tamak moraha khali siteo sirf7alak o ghayb9at yt7sab lwa9t max sa3a

**Comment by Twilight392** [comment]
diro inspecter elements copiw dak script f console oghayb9a khdam bohdo (kayjawb 3chwa2iyan)

**Comment by hawd-vfx** [comment]
B7al l'blan dyal auto-click

**Comment by Tab1000j** [comment]
> diro inspecter elements o copiw dak script f console oghayb9a khdam bohdo (kayjawb 3chwa2iyan)

khouya ana b2 w tb9t les etap li glti walakin howa ghir kayskiper les question makaykhtarx xi repance
![Capture](https://github.com/user-attachments/assets/4671e998-538c-4eaf-994a-3a15f285d600)

**Comment by Twilight392** [comment]
li la7edt flenglish kijawb o francais la (fga3 l7alat rah kayzid lw9t).

**Comment by VMN842** [comment]
GUYS DB KIDRTO 7LITO LMOCHKIL

**Comment by zacariahh** [comment]
mafiha ta chi risk bach i3i9o bina wla chi haja yak???

**Comment by aminessbaa** [comment]
> mafiha ta chi risk bach i3i9o bina wla chi haja yak???
tzadolik swaya3 yk?
