### ISSUE TITLE
Rosetta Stone MOROCCO

### ISSUE THREAD

**Issue by s11dkl** [m1dugh/RosettaStonks#89]

**Comment by s11dkl** [comment]
Mhm l aya wahd kidir autoclicker rah kolchi ghadi yt3aqb hit rah kolshi kitle3 endhum, ama nass dyal had lcode 🙂🙂 lah isbrkum rah c'est pire 
Mhm ana gher kn7drkom, lahoma matdirhach ga3 o doz ratt oula dirha kamla zayda o ydiro lik fraude o ymshi lik lmodule oula l3am kaml ga3 !!!!
Ykoun kheir

**Comment by AAAAAAAAAAAAYYYYYYYYYYYYYMMMMMMMMMMM** [comment]
how can you tell

**Comment by Twilight392** [comment]
Trust me bro

**Comment by AAAAAAAAAAAAYYYYYYYYYYYYYMMMMMMMMMMM** [comment]
> Trust me bro

a kichyro alors que daba baqi matra tahaja w magalo tahaja

**Comment by s11dkl** [comment]
> how can you tell
> 
> 

Mli tlqa smitk fwahd la liste dik saea njwbk 😀

**Comment by Arthur-code01** [comment]
lkhot hd hdra mkinach kn3rf ch7l mn wa7d daz bhdchi o dwz exam o mkina la fraude la wlo o dik la liste li kador raha fake syboha hadok likibi3o bch i7takro !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by AAAAAAAAAAAAYYYYYYYYYYYYYMMMMMMMMMMM** [comment]
> > how can you tell
> 
> Mli tlqa smitk fwahd la liste dik saea njwbk 😀

KHRJAT LISTE WHDA AND IT'S FAKE

**Comment by zacariahh** [comment]
ina ratt?? hhhhhhh rah ila makmltich magatdwezch mtihan w lamadewztich  atb9alik gha 40 f mya dyal presentiel ateyehlik gha no9ta en plus rah makayn walo mn hdertek w 3ndi prove mn support dial rosetta nl9a tswira nsiftha lik w tahiyati

**Comment by LoopWasTaken** [comment]
A

> _No description provided._

Rak akat5rb9 hhh lafac fiha 6000 wa7d biti kola wa7d iverifiw lih dkchi

**Comment by houssam15** [comment]
lay sehel 3la drari

**Comment by moha20065** [comment]
> _No description provided._

Wd 9 baghi tby3 lihom l3jl hh
Ikhwan khdmo brahtkom

**Comment by s11dkl** [comment]
Mhm ankhtasser likum kaaamlin? Ntlaqaw mora mtkhrej la liste 👋🏻👋🏻
