### ISSUE TITLE
chi 2 wla 3 drari n9ado chi script dyl flucy builder

### ISSUE THREAD

**Issue by houssam15** [m1dugh/RosettaStonks#96]

**Comment by BXRl** [comment]
me

**Comment by moha20065** [comment]
Interesting

**Comment by moha20065** [comment]
> chi whd fikom i9ad chi repo 

3ndk discord

**Comment by houssam15** [comment]
ui mais mkndkhlch lih bzaf

**Comment by houssam15** [comment]
sift liya msg houssfrty0940

**Comment by ricardo-milos884** [comment]
lqito chi solution??

**Comment by moha20065** [comment]
> sift liya msg houssfrty0940
> 

Okay

**Comment by moha20065** [comment]
> sift liya msg houssfrty0940
>

**Comment by houssam15** [comment]
> > sift liya msg houssfrty0940
> 
> Acceptini dayr fih wahd lhota

mwsli ta invite

**Comment by houssam15** [comment]
https://discord.gg/Xy2wEEra
