### ISSUE TITLE
drari chi 7al rani zedt ktr mn 15h bl ghalat wch kyn kifch n9shom ?

### ISSUE THREAD

**Issue by koolyasso** [m1dugh/RosettaStonks#99]
**Describe the bug**

**Browser**
- [ ] firefox
- [ ] chrome

**version**: 

**rosettastone product**
- [ ] Foundations
- [ ] Fluency builder

**To Reproduce**

**Expected behavior**

**Comment by houssam15** [comment]
mo7l

**Comment by fath0l** [comment]
khoya  ana mabghawch itzado liya 3lach khdmat liya f ang o fr la

**Comment by S1LVER-ST** [comment]
KHOYA ANA MABGHACH GA3 YKHDMLI MA3RFTCH 3LACH

**Comment by zacariahh** [comment]
rah asat welat kat3etel bzaaaaaaaaaaaaaaaaaaaf makatzidch f blasa
mhm tsna nta w zehrek kayn li kigol tzad lih mn wra chi 1j kayn wahd gal 5j ga3 mhm
dars mn hadchi howa khdem b had script f s2 f lwl ta3ha hit f lwl script kan khedam toute suite db wla 3lih deght wla kit3etel tahiyati
